import net.liftweb.mapper._
import net.liftweb.util.Helpers._
import scala.xml._

class Item extends LongKeyedMapper[Item] {
  def getSingleton = Item
  
	def primaryKeyField = tmdbId
  object tmdbId extends MappedLongIndex(this) {
    override def writePermission_? = true
    override def dbAutogenerated_? = false
	}
	
  object name extends MappedText(this)	
}

object Item extends Item with LongKeyedMetaMapper[Item] {

}
